development:
  adapter: postgresql
  encoding: utf8
  database: upesteem_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: upesteem_test
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: upesteem_production
  host: localhost
